// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'it'
	| 'pl'
	| 'pt'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	counter: NamespaceCounterTranslation,
	features: NamespaceFeaturesTranslation
}

type RootTranslation = {
	/**
	 * C​u​r​r​e​n​t​ ​l​a​n​g​u​a​g​e​:​ ​{​l​o​c​a​l​e​}
	 * @param {string} locale
	 */
	currentLanguage: RequiredParams<'locale'>
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	greeting: RequiredParams<'name'>
	/**
	 * L​o​a​d​ ​"​{​n​a​m​e​s​p​a​c​e​}​"​ ​n​a​m​e​s​p​a​c​e
	 * @param {string} namespace
	 */
	loadNamespace: RequiredParams<'namespace'>
	/**
	 * L​o​a​d​e​d​ ​n​a​m​e​s​p​a​c​e​s​:​ ​{​n​a​m​e​s​p​a​c​e​s​}
	 * @param {string} namespaces
	 */
	namespacesLoaded: RequiredParams<'namespaces'>
	/**
	 * S​w​i​t​c​h​ ​l​a​n​g​u​a​g​e
	 */
	switchLanguage: string
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​t​h​e​ ​t​y​p​e​s​a​f​e​-​i​1​8​n​ ​R​e​a​c​t​ ​s​a​m​p​l​e​ ​a​p​p​.
	 */
	welcome: string
}

export type NamespaceCounterTranslation = {
	/**
	 * C​o​u​n​t​:​ ​{​c​o​u​n​t​}
	 * @param {number} count
	 */
	count: RequiredParams<'count'>
	/**
	 * D​e​c​r​e​m​e​n​t
	 */
	decrement: string
	/**
	 * I​n​c​r​e​m​e​n​t
	 */
	increment: string
	/**
	 * C​o​u​n​t​e​r
	 */
	title: string
}

export type NamespaceFeaturesTranslation = {
	/**
	 * A​u​t​o​-​c​o​m​p​l​e​t​i​o​n​ ​i​n​ ​y​o​u​r​ ​I​D​E
	 */
	autoCompletion: string
	/**
	 * N​a​m​e​s​p​a​c​e​ ​s​u​p​p​o​r​t​ ​f​o​r​ ​o​n​-​d​e​m​a​n​d​ ​l​o​a​d​i​n​g
	 */
	namespaces: string
	/**
	 * S​m​a​l​l​ ​b​u​n​d​l​e​ ​s​i​z​e
	 */
	smallBundle: string
	/**
	 * F​e​a​t​u​r​e​s
	 */
	title: string
	/**
	 * F​u​l​l​ ​t​y​p​e​-​s​a​f​e​t​y​ ​f​o​r​ ​t​r​a​n​s​l​a​t​i​o​n​s
	 */
	typeSafety: string
}

export type Namespaces =
	| 'counter'
	| 'features'

type DisallowNamespaces = {
	/**
	 * reserved for 'counter'-namespace\
	 * you need to use the `./counter/index.ts` file instead
	 */
	counter?: "[typesafe-i18n] reserved for 'counter'-namespace. You need to use the `./counter/index.ts` file instead."

	/**
	 * reserved for 'features'-namespace\
	 * you need to use the `./features/index.ts` file instead
	 */
	features?: "[typesafe-i18n] reserved for 'features'-namespace. You need to use the `./features/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Current language: {locale}
	 */
	currentLanguage: (arg: { locale: string }) => LocalizedString
	/**
	 * Hello {name}!
	 */
	greeting: (arg: { name: string }) => LocalizedString
	/**
	 * Load "{namespace}" namespace
	 */
	loadNamespace: (arg: { namespace: string }) => LocalizedString
	/**
	 * Loaded namespaces: {namespaces}
	 */
	namespacesLoaded: (arg: { namespaces: string }) => LocalizedString
	/**
	 * Switch language
	 */
	switchLanguage: () => LocalizedString
	/**
	 * Welcome to the typesafe-i18n React sample app.
	 */
	welcome: () => LocalizedString
	counter: {
		/**
		 * Count: {count}
		 */
		count: (arg: { count: number }) => LocalizedString
		/**
		 * Decrement
		 */
		decrement: () => LocalizedString
		/**
		 * Increment
		 */
		increment: () => LocalizedString
		/**
		 * Counter
		 */
		title: () => LocalizedString
	}
	features: {
		/**
		 * Auto-completion in your IDE
		 */
		autoCompletion: () => LocalizedString
		/**
		 * Namespace support for on-demand loading
		 */
		namespaces: () => LocalizedString
		/**
		 * Small bundle size
		 */
		smallBundle: () => LocalizedString
		/**
		 * Features
		 */
		title: () => LocalizedString
		/**
		 * Full type-safety for translations
		 */
		typeSafety: () => LocalizedString
	}
}

export type Formatters = {}
