// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import de from './de'
import en from './en'
import es from './es'
import fr from './fr'
import it from './it'
import pl from './pl'
import pt from './pt'

import de_counter from './de/counter'
import de_features from './de/features'
import en_counter from './en/counter'
import en_features from './en/features'
import es_counter from './es/counter'
import es_features from './es/features'
import fr_counter from './fr/counter'
import fr_features from './fr/features'
import it_counter from './it/counter'
import it_features from './it/features'
import pl_counter from './pl/counter'
import pl_features from './pl/features'
import pt_counter from './pt/counter'
import pt_features from './pt/features'

const localeTranslations = {
	de: {
		...de,
		counter: de_counter,
		features: de_features
	},
	en: {
		...en,
		counter: en_counter,
		features: en_features
	},
	es: {
		...es,
		counter: es_counter,
		features: es_features
	},
	fr: {
		...fr,
		counter: fr_counter,
		features: fr_features
	},
	it: {
		...it,
		counter: it_counter,
		features: it_features
	},
	pl: {
		...pl,
		counter: pl_counter,
		features: pl_features
	},
	pt: {
		...pt,
		counter: pt_counter,
		features: pt_features
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
